root: true

env:
    es6: true
    browser: true
    node: true
    mocha: true

parserOptions:
    ecmaVersion: 8
    sourceType: "module"

extends: "eslint:recommended"

rules:
    indent: [ 2, "tab", { SwitchCase: 1 } ]
    semi: [ 2, "always" ]
    keyword-spacing: [ 2, { before: true, after: true } ]
    space-before-blocks: [ 2, "always" ]
    space-before-function-paren: [ 2, "always" ]
    no-mixed-spaces-and-tabs: [ 2, "smart-tabs" ]
    no-cond-assign: 0
    no-unused-vars: 2
    object-shorthand:  [ 2, "always" ]
    no-const-assign: 2
    no-class-assign: 2
    no-this-before-super: 2
    no-var: 2
    no-unreachable: 0
    valid-typeof: 2
    quote-props: [ 2, "as-needed" ]
    one-var: [ 2, "never" ]
    prefer-arrow-callback: 2
    prefer-const: [ 2, { destructuring: "all" } ]
    arrow-spacing: 2
    no-irregular-whitespace: 0
    no-console: 0
